# Generated by Django 3.2.3 on 2021-05-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_type', models.CharField(max_length=5)),
                ('bedrooms', models.CharField(max_length=3)),
                ('floor', models.CharField(max_length=3)),
                ('lift', models.CharField(max_length=4)),
                ('kitchen', models.CharField(max_length=4)),
                ('bathroom', models.CharField(max_length=4)),
                ('electricity', models.CharField(max_length=4)),
                ('water', models.CharField(max_length=4)),
                ('living', models.CharField(max_length=4)),
                ('gallery', models.CharField(max_length=4)),
                ('wifi', models.CharField(max_length=4)),
                ('tv', models.CharField(max_length=4)),
                ('pets', models.CharField(max_length=4)),
                ('rent', models.IntegerField()),
                ('vacancies', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
    ]
