# Generated by Django 3.2.3 on 2021-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NewCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=20)),
                ('lname', models.TextField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('gender', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.TextField(max_length=10)),
                ('username', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
                ('password1', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
            ],
        ),
    ]
