# Generated by Django 3.2.3 on 2021-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_helpdesk_newcustomer_registeredcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='email',
            field=models.TextField(max_length=30),
        ),
    ]
